[build]
  publish = "."
  command = "npm run build"

[build.environment]
  VITE_SUPABASE_URL = "https://gptacdyjxmjzlmgwjmms.supabase.co"
  # VITE_SUPABASE_KEY在Netlify的环境变量设置中配置

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200