[build]
  publish = "."
  command = "node build.js"

[build.environment]
  VITE_SUPABASE_KEY = ""
  VITE_SUPABASE_URL = "https://gptacdyjxmjzlmgwjmms.supabase.co"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200